### ISSUE TITLE
Not respecting LISTEN_PORT

### ISSUE THREAD

**Issue by barcar** [JosephRPalmer/ecowitt-bridge#1]
Thanks for developing this. I'm trying to set it up to listen on a different port (8084).

My Docker Compose contains:

```
    network_mode: host
    restart: always
    environment:
      - LISTEN_PORT=8084
 ```

But in the logs it is still listening on 8082:

```
Listening on port 8082 and resending to...
``` 

Do I need to do something else for this to work correctly? Thanks for any tips.
